[package]
name = "isdown-notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
dns-lookup = "2.0.4"
formatify = "0.2.0"
gethostname = "1.0.2"
surge-ping = "0.8.2"
tokio = { version = "1.45.0", features = ["full"] }
toml = "0.8.22"
webhook = "2.1.2"
