delay = 20
timeout = 5
retry = 5

# "name" = "ip"
[hosts]
"Google" = "google.com"

[discord]
webhook = "" # discord webhook url
content = "At <t:%(unix_timestamp)>"
embed_content = "%(name) (%(ip)) is %(status)"

# opens a webpage when google is offline
[execute_on_offline]
"Google" = [
    "npx live-server"
]
